### ISSUE TITLE
CORS not found in APK build, ionic 4

### ISSUE THREAD

**Issue by itsandrehere** [driftyco/ionic-proxy-example#5]
in ionic serve cors is working in browser but not working apk

. In the browser (using ionic serve) it was working properly , but in apk (using ionic build android ) it was not working........

cordova plugin add cordova-plugin-whitelist (I have added this puigin using CLI)

I have used these things in config.xml

ionic.project
{
"name": "ap",
"proxies": [
{
"path": "/api",
"proxyUrl": "http://dev.alquiloparticular.com"
}
]
}

**Comment by perrygovier** [comment]
Hey Mike, does wkwebview respect cordova CORS exceptions?

**Comment by mhartington** [comment]
Hi there! the proxy config in the ionic.config.json is only meant for `ionic serve`, as temporary work-around. Once deployed to a real device (ios or android), the API must be set up correct to allow for cross-origin requests. 

https://ionicframework.com/docs/faq/cors
